[project]
name = "auth-almighty"
version = "0.1.0"
description = ""
authors = [
    {name = "LaProgrammer",email = "justin.ebedi@uricreative.com"}
]
readme = "README.md"
requires-python = ">=2.7"
dependencies = [
]

[tool.poetry]
packages = [{include = "auth_almighty", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
